import type { Metadata } from "next";
import { Recursive as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn("font-sans antialiased", fontSans.variable)}>
                <main className="min-h-screen flex flex-col bg-background">
                    <div className="flex-1 flex flex-col h-full">{children}</div>
                    <Footer />
                </main>
            </body>
        </html>
    );
}
